### ISSUE TITLE
Rollup User To Cource

### ISSUE THREAD

**Issue by nesterone** [Mentorioum/mentoriumbot#1]
Implement the next interaction with mentobot
[Rollup to course conversion ](https://github.com/Mentorioum/mentorioum-docs/tree/dfe412133c209540e049249c87615ffb0ff947a6)

**Comment by 0pdd** [comment]
@nesterone the puzzle [#2](https://github.com/Mentorioum/mentoriumbot/issues/2) is still not solved.

**Comment by 0pdd** [comment]
@nesterone 2 puzzles [#3](https://github.com/Mentorioum/mentoriumbot/issues/3), [#4](https://github.com/Mentorioum/mentoriumbot/issues/4) are still not solved; solved: [#2](https://github.com/Mentorioum/mentoriumbot/issues/2).

**Comment by 0pdd** [comment]
@nesterone the puzzle [#4](https://github.com/Mentorioum/mentoriumbot/issues/4) is still not solved; solved: [#2](https://github.com/Mentorioum/mentoriumbot/issues/2), [#3](https://github.com/Mentorioum/mentoriumbot/issues/3).

**Comment by 0pdd** [comment]
@nesterone the puzzle [#5](https://github.com/Mentorioum/mentoriumbot/issues/5) is still not solved; solved: [#2](https://github.com/Mentorioum/mentoriumbot/issues/2), [#3](https://github.com/Mentorioum/mentoriumbot/issues/3), [#4](https://github.com/Mentorioum/mentoriumbot/issues/4).

**Comment by nesterone** [comment]
let me mention myself @nesterone

**Comment by 0pdd** [comment]
@nesterone the puzzle [#6](https://github.com/Mentorioum/mentoriumbot/issues/6) is still not solved; solved: [#2](https://github.com/Mentorioum/mentoriumbot/issues/2), [#3](https://github.com/Mentorioum/mentoriumbot/issues/3), [#4](https://github.com/Mentorioum/mentoriumbot/issues/4), [#5](https://github.com/Mentorioum/mentoriumbot/issues/5).

**Comment by 0pdd** [comment]
@nesterone 2 puzzles [#7](https://github.com/Mentorioum/mentoriumbot/issues/7), [#8](https://github.com/Mentorioum/mentoriumbot/issues/8) are still not solved; solved: [#2](https://github.com/Mentorioum/mentoriumbot/issues/2), [#3](https://github.com/Mentorioum/mentoriumbot/issues/3), [#4](https://github.com/Mentorioum/mentoriumbot/issues/4), [#5](https://github.com/Mentorioum/mentoriumbot/issues/5), [#6](https://github.com/Mentorioum/mentoriumbot/issues/6).

**Comment by igornester** [comment]
@nesterone  test

**Comment by 0pdd** [comment]
@nesterone all 7 puzzles are solved here: [#2](https://github.com/Mentorioum/mentoriumbot/issues/2), [#3](https://github.com/Mentorioum/mentoriumbot/issues/3), [#4](https://github.com/Mentorioum/mentoriumbot/issues/4), [#5](https://github.com/Mentorioum/mentoriumbot/issues/5), [#6](https://github.com/Mentorioum/mentoriumbot/issues/6), [#7](https://github.com/Mentorioum/mentoriumbot/issues/7), [#8](https://github.com/Mentorioum/mentoriumbot/issues/8).
