### ISSUE TITLE
notification.service.ts:6-7: Define start/stop endpoint...

### ISSUE THREAD

**Issue by 0pdd** [Mentorioum/mentoriumbot#18]
The puzzle `9-b20f3e92` from #9 has to be resolved: 

https://github.com/Mentorioum/mentoriumbot/blob/f337c729e4f4592a8d05f8f7c000915109917409/src/notification.service.ts#L6-L7

The puzzle was created by nesterone on 25-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nesterone** [comment]
Hi, @walle010101

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
The puzzle `9-b20f3e92` has disappeared from the source code, that's why I closed this issue.

**Comment by walle010101** [comment]
Hi there ! 0pdd
