### ISSUE TITLE
notification.service.ts:51-53: Bot as collaborator get's...

### ISSUE THREAD

**Issue by 0pdd** [Mentorioum/mentoriumbot#35]
The puzzle `30-9ace3331` from #30 has to be resolved: 

https://github.com/Mentorioum/mentoriumbot/blob/a42f59b2306e55a740a371a9b4003f1837ca6434/src/notification.service.ts#L51-L53

The puzzle was created by nesterone on 14-Mar-20. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
The puzzle `30-9ace3331` has disappeared from the source code, that's why I closed this issue.

**Comment by walle010101** [comment]
Hi there ! 0pdd
