### ISSUE TITLE
notification.service.ts:73: - parse issue.body to get...

### ISSUE THREAD

**Issue by 0pdd** [Mentorioum/mentoriumbot#39]
The puzzle `32-7bc93630` from #32 has to be resolved: 

https://github.com/Mentorioum/mentoriumbot/blob/c93ac2f519b1d95645ee4f3c321a397ec23cf695/src/notification.service.ts#L73-L73

The puzzle was created by nesterone on 21-Mar-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
The puzzle `32-7bc93630` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#41](https://github.com/Mentorioum/mentoriumbot/issues/41), [#42](https://github.com/Mentorioum/mentoriumbot/issues/42) are still not solved.

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#46](https://github.com/Mentorioum/mentoriumbot/issues/46), [#47](https://github.com/Mentorioum/mentoriumbot/issues/47), [#48](https://github.com/Mentorioum/mentoriumbot/issues/48), [#49](https://github.com/Mentorioum/mentoriumbot/issues/49), [#50](https://github.com/Mentorioum/mentoriumbot/issues/50), [#51](https://github.com/Mentorioum/mentoriumbot/issues/51) are still not solved; solved: [#41](https://github.com/Mentorioum/mentoriumbot/issues/41), [#42](https://github.com/Mentorioum/mentoriumbot/issues/42).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#46](https://github.com/Mentorioum/mentoriumbot/issues/46), [#47](https://github.com/Mentorioum/mentoriumbot/issues/47), [#48](https://github.com/Mentorioum/mentoriumbot/issues/48), [#50](https://github.com/Mentorioum/mentoriumbot/issues/50), [#51](https://github.com/Mentorioum/mentoriumbot/issues/51), [#52](https://github.com/Mentorioum/mentoriumbot/issues/52) are still not solved; solved: [#41](https://github.com/Mentorioum/mentoriumbot/issues/41), [#42](https://github.com/Mentorioum/mentoriumbot/issues/42), [#49](https://github.com/Mentorioum/mentoriumbot/issues/49).

**Comment by walle010101** [comment]
Hi there ! 0pdd
