### ISSUE TITLE
markdown.links.ts:8: Extend with parsing assignee and...

### ISSUE THREAD

**Issue by 0pdd** [Mentorioum/mentoriumbot#41]
The puzzle `39-e4818b3a` from #39 has to be resolved: 

https://github.com/Mentorioum/mentoriumbot/blob/550fef15efcdc6cabcb3cbb72183d7d084ee30a9/src/markdown.links.ts#L8-L8

The puzzle was created by nesterone on 23-Mar-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@0pdd the puzzle [#46](https://github.com/Mentorioum/mentoriumbot/issues/46) is still not solved.

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
