### ISSUE TITLE
notification.service.ts:12-13: Provide proper time/since...

### ISSUE THREAD

**Issue by 0pdd** [Mentorioum/mentoriumbot#6]
The puzzle `1-8be40431` from #1 has to be resolved: 

https://github.com/Mentorioum/mentoriumbot/blob/35d665331d78cd6d8ad4190623063eb5d28d1b7b/src/notification.service.ts#L12-L13

The puzzle was created by igornester on 27-Dec-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nesterone** [comment]
mention again to test in other issue @nesterone

**Comment by 0pdd** [comment]
The puzzle `1-8be40431` has disappeared from the source code, that's why I closed this issue.
